# frozen_string_literal: true

module Ea
  module Sources
    module Qea
      # EA AUTO-GENERATED "Context Diagram" support.
      #
      # Context diagrams are regenerated by EA at DRAW time from the
      # model, so the stored t_diagramlinks rows are stale:
      #
      #   - Hidden rows are NEVER drawn (B6847577: 42 Hidden=1
      #     dependencies, zero rendered).
      #   - Every drawn connector is a DIRECT line: the straight
      #     segment between the two box-outline crossings of the
      #     center-to-center ray (verified: B6847577 focal left-edge
      #     dock predicted 171.8 vs EA 171; E58034A3's 22 visible
      #     links all render straight despite stale EDGE geometry).
      #   - Package contexts ("Context Diagram: Package
      #     Clients|Suppliers of X") synthesize ONE extra line per
      #     placed object carrying a model Dependency with the focal
      #     package X, unless a visible link already connects the
      #     pair (B6847577: 15 synthesized + 2 visible = 17 drawn).
      #     When the focal is not placed exactly once, nothing
      #     synthesizes (E02FA330: 7 placed suppliers, 0 lines).
      module ContextDiagramSupport
        NAME_PREFIX = "context diagram"
        PACKAGE_PATTERN = /\AContext Diagram: Package (Clients|Suppliers) of (.+)\z/i
        FOCAL_CONNECTOR_TYPES = %w[Dependency].freeze

        module_function

        def context?(diagram_row)
          diagram_row.name.to_s.downcase.start_with?(NAME_PREFIX)
        end

        # {"variant" => "Clients"|"Suppliers", "focal_name" => X}
        # for package contexts, nil otherwise.
        def package_context(diagram_row)
          match = PACKAGE_PATTERN.match(diagram_row.name.to_s)
          return nil unless match

          # The name after "of " is matched VERBATIM: EA stores
          # object names with their own whitespace ("of  Topology
          # Simple" pairs the object " Topology Simple").
          { "variant" => match[1].capitalize, "focal_name" => match[2] }
        end

        # Placed-object rows for the focal package (exact name match),
        # or [] — callers synthesize only when exactly one exists.
        def focal_placements(diagram_row, database)
          pkg = package_context(diagram_row)
          return [] unless pkg

          placements = database.diagram_objects_for(diagram_row.diagram_id) || []
          placements.select do |placement|
            obj = database.find_object(placement.ea_object_id.to_i)
            obj && obj.name.to_s == pkg["focal_name"]
          end
        end

        # EA object IDs of placed elements that carry a model
        # Dependency with the focal package, minus pairs already
        # connected by a visible link row.
        def autoline_candidates(diagram_row, database)
          pkg = package_context(diagram_row)
          return {} unless pkg

          focal_rows = focal_placements(diagram_row, database)
          return {} unless focal_rows.size == 1

          focal_id = focal_rows.first.ea_object_id.to_i
          placed_ids = placed_object_ids_for(diagram_row, database)
          visible = visible_focal_partners(diagram_row, database, focal_id)

          into_focal = pkg["variant"] == "Clients"
          candidates = {}
          (database.collections[:connectors] || []).each do |conn|
            next unless FOCAL_CONNECTOR_TYPES.include?(conn.connector_type)

            start_id = conn.start_object_id.to_i
            end_id = conn.end_object_id.to_i
            other = if into_focal && end_id == focal_id
                      start_id
                    elsif !into_focal && start_id == focal_id
                      end_id
                    end
            next unless other
            next unless placed_ids.include?(other)
            next if visible.include?(other)

            candidates[other] ||= conn
          end
          candidates
        end

        # SuppressFOC=1 in t_diagram.StyleEx freezes an element
        # context diagram to its stored visible links; absent or 0
        # makes EA regenerate ALL model connectors among the placed
        # elements (568CDFC9 draws all 10 incl. hidden rows'
        # connectors; 3072804C/801EEB12 with =1 draw visible rows
        # only).
        def element_regenerate?(diagram_row)
          return false if package_context(diagram_row)

          diagram_row.styleex.to_s.match(/SuppressFOC=(\d)/)&.public_send(:[], 1) != "1"
        end

        # t_connector rows EA regenerates for a SuppressFOC=0 element
        # context: connectors among the placed elements that touch
        # the focal, plus "star" links joining a focal neighbour to a
        # non-neighbour (E0790EFC draws the 8 focal links and skips
        # the ring1-ring1 web; 85039DAE draws ring2-ring1 and skips
        # ring2-ring2). Ring1-ring1 links never draw. Self-loops of
        # the focal included. Hidden rows do not block regeneration;
        # visible rows keep their stored rendering instead.
        def regenerated_element_connectors(diagram_row, database)
          return [] unless element_regenerate?(diagram_row)

          placed_ids = placed_object_ids_for(diagram_row, database)
          visible_conn_ids = (database.diagram_links_for(diagram_row.diagram_id) || [])
                             .reject { |link| link.hidden.to_i.nonzero? }
                             .map(&:connectorid).compact.to_set
          focal_id = focal_element_id(diagram_row, database, placed_ids)
          neighbours = focal_neighbours(database, focal_id)
          (database.collections[:connectors] || []).filter_map do |conn|
            next nil if conn.connector_type == "Nesting"
            next nil unless placed_ids.include?(conn.start_object_id.to_i)
            next nil unless placed_ids.include?(conn.end_object_id.to_i)
            next nil if visible_conn_ids.include?(conn.connector_id)
            next nil unless regenerated_pair?(conn, focal_id, neighbours)

            conn
          end
        end

        def focal_element_id(diagram_row, database, placed_ids)
          focal_name = diagram_row.name.to_s
                              .sub(/\AContext [Dd]iagram:\s*/, "")
                              .strip
          focal = (database.diagram_objects_for(diagram_row.diagram_id) || [])
                  .select do |placement|
            obj = database.find_object(placement.ea_object_id.to_i)
            obj && obj.name.to_s == focal_name
          end
          return focal.first.ea_object_id.to_i if focal.size == 1

          # Renamed focus: EA keeps drawing the original element's
          # context ("Context Diagram: TS_Feature" still renders the
          # TS_FeatureComponent star after the rename). Fall back to
          # the placed element most connected WITHIN the placed set
          # (global model degree is misleading — GM_Composite links
          # to hundreds of off-diagram elements).
          degree = Hash.new(0)
          (database.collections[:connectors] || []).each do |conn|
            start_id = conn.start_object_id.to_i
            end_id = conn.end_object_id.to_i
            next unless placed_ids.include?(start_id) &&
                        placed_ids.include?(end_id)

            degree[start_id] += 1
            degree[end_id] += 1
          end
          placed_ids.max_by { |id| [degree[id], -id] }
        end

        def focal_neighbours(database, focal_id)
          return Set.new unless focal_id

          neighbours = Set.new
          (database.collections[:connectors] || []).each do |conn|
            next if conn.connector_type == "Nesting"

            neighbours << conn.end_object_id.to_i if conn.start_object_id.to_i == focal_id
            neighbours << conn.start_object_id.to_i if conn.end_object_id.to_i == focal_id
          end
          neighbours
        end

        def regenerated_pair?(conn, focal_id, neighbours)
          return false unless focal_id

          start_id = conn.start_object_id.to_i
          end_id = conn.end_object_id.to_i
          return true if start_id == focal_id || end_id == focal_id

          (neighbours.include?(start_id) ? 1 : 0) +
            (neighbours.include?(end_id) ? 1 : 0) == 1
        end

        def placed_object_ids_for(diagram_row, database)
          (database.diagram_objects_for(diagram_row.diagram_id) || [])
            .map { |p| p.ea_object_id.to_i }
        end

        # Object IDs whose pair with the focal is already drawn by a
        # visible link row (connector exists, both ends placed).
        def visible_focal_partners(diagram_row, database, focal_id)
          placed_ids = placed_object_ids_for(diagram_row, database)
          partners = []
          (database.diagram_links_for(diagram_row.diagram_id) || []).each do |link|
            next if link.hidden.to_i.nonzero?

            conn = database.find_connector(link.connectorid)
            next unless conn

            start_id = conn.start_object_id.to_i
            end_id = conn.end_object_id.to_i
            next unless placed_ids.include?(start_id) && placed_ids.include?(end_id)
            next unless start_id == focal_id || end_id == focal_id

            partners << (start_id == focal_id ? end_id : start_id)
          end
          partners
        end
      end
    end
  end
end
