# frozen_string_literal: true

require "lutaml/model"

module Ea
  module Qea
    module Models
      autoload :BaseModel, "ea/qea/models/base_model"
      autoload :EaAttribute, "ea/qea/models/ea_attribute"
      autoload :EaAttributeTag, "ea/qea/models/ea_attribute_tag"
      autoload :EaComplexityType, "ea/qea/models/ea_complexity_type"
      autoload :EaConnector, "ea/qea/models/ea_connector"
      autoload :EaConnectorType, "ea/qea/models/ea_connector_type"
      autoload :EaConstraintType, "ea/qea/models/ea_constraint_type"
      autoload :EaDatatype, "ea/qea/models/ea_datatype"
      autoload :EaDiagram, "ea/qea/models/ea_diagram"
      autoload :EaDiagramLink, "ea/qea/models/ea_diagram_link"
      autoload :EaDiagramObject, "ea/qea/models/ea_diagram_object"
      autoload :EaDiagramType, "ea/qea/models/ea_diagram_type"
      autoload :EaDocument, "ea/qea/models/ea_document"
      autoload :EaImage, "ea/qea/models/ea_image"
      autoload :EaGlossary, "ea/qea/models/ea_glossary"
      autoload :EaList, "ea/qea/models/ea_list"
      autoload :EaVersion, "ea/qea/models/ea_version"
      autoload :EaPhase, "ea/qea/models/ea_phase"
      autoload :EaAuthor, "ea/qea/models/ea_author"
      autoload :EaSecrypt, "ea/qea/models/ea_secrypt"
      autoload :EaPalette, "ea/qea/models/ea_palette"
      autoload :EaPaletteItem, "ea/qea/models/ea_palette_item"
      autoload :EaImplement, "ea/qea/models/ea_implement"
      autoload :EaRoleConstraint, "ea/qea/models/ea_role_constraint"
      autoload :EaObjectProblem, "ea/qea/models/ea_object_problem"
      autoload :EaObjectRisk, "ea/qea/models/ea_object_risk"
      autoload :EaObjectTest, "ea/qea/models/ea_object_test"
      autoload :EaObjectEffort, "ea/qea/models/ea_object_effort"
      autoload :EaObjectResource, "ea/qea/models/ea_object_resource"
      autoload :EaObjectScenario, "ea/qea/models/ea_object_scenario"
      autoload :EaObjectRequire, "ea/qea/models/ea_object_require"
      autoload :EaObjectTrx, "ea/qea/models/ea_object_trx"
      autoload :EaObject, "ea/qea/models/ea_object"
      autoload :EaObjectConstraint, "ea/qea/models/ea_object_constraint"
      autoload :EaObjectProperty, "ea/qea/models/ea_object_property"
      autoload :EaObjectType, "ea/qea/models/ea_object_type"
      autoload :EaOperation, "ea/qea/models/ea_operation"
      autoload :EaOperationParam, "ea/qea/models/ea_operation_param"
      autoload :EaPackage, "ea/qea/models/ea_package"
      autoload :EaScript, "ea/qea/models/ea_script"
      autoload :EaStatusType, "ea/qea/models/ea_status_type"
      autoload :EaStereotype, "ea/qea/models/ea_stereotype"
      autoload :EaTaggedValue, "ea/qea/models/ea_tagged_value"
      autoload :EaXref, "ea/qea/models/ea_xref"
    end
  end
end
